
import Head from "next/head";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { getSession, useSession } from "next-auth/react";

import axios from "axios";
import { redirect } from "next/navigation";
import Main from "@/components/home/main";
import FlashDeals from "@/components/home/flashDeals";
import Category from "@/components/home/category";
import { gamingSwiper, homeImprovSwiper, women_accessories, women_dresses, women_shoes, women_swiper } from "@/data/home";
import ProductSwiper from "@/components/productSwiper";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const {data:session} = useSession();


            
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.home}>
        <div className={styles.container}>
          <Main/>
          <FlashDeals/>
          <div className={styles.home__category}>
            <Category header="Dresses" products={women_dresses} background="#5a31f4"/>
            <Category header="Shoes / High Heels" products={women_shoes} background="#3c811f"/>
            <Category header="Accessories" products={women_accessories} background="#000"/>
          </div>
          <ProductSwiper  products={women_swiper}/>
          <ProductSwiper  products={gamingSwiper}/>
          <ProductSwiper  products={homeImprovSwiper}/>
        </div>
      </div>
     
    </>
  );
}
